import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const cards = [
  "Mande um direct com um emoji de fogo para a 3ª pessoa nos seus stories.",
  "Dê um beijo no pescoço da pessoa à sua esquerda.",
  "Confesse qual é a sua posição favorita e descreva brevemente.",
  "Qual foi a última coisa mais safada que você pesquisou no celular?",
  "Se você pudesse passar uma noite com qualquer pessoa nesta sala, quem seria?",
  "Fique de olhos vendados por uma rodada e adivinhe quem está tocando seu rosto.",
  "Mande uma mensagem dizendo 'Pensei em você...' para a última pessoa com quem flertou.",
  "Mostre a última foto da sua galeria que você não mostraria para os seus pais.",
  "Diga o que você achou mais atraente na primeira vez que viu a pessoa à sua frente.",
  "Dê uma mordidinha leve na orelha da pessoa à sua direita.",
  "Qual é o seu maior 'turn on' em um encontro?",
  "Sussurre um segredo íntimo ou uma fantasia no ouvido de alguém da roda.",
  "Se tivéssemos que ficar presos em um elevador, o que você gostaria que fizéssemos?",
  "Deixe a pessoa à sua frente ver as suas últimas 5 fotos enviadas no WhatsApp.",
  "Quem aqui você acha que tem o melhor beijo, apenas julgando pela aparência?",
  "Faça uma massagem sensual nos ombros da pessoa à sua direita por 1 minuto.",
  "Qual foi o lugar mais inusitado onde você já fez amor?",
  "Diga duas coisas que você faria comigo se estivéssemos sozinhos em um quarto escuro.",
  "Beba um shot ou deixe que a pessoa à sua esquerda envie uma mensagem de flerte do seu celular.",
  "Qual é o seu maior fetiche que você tem vergonha de admitir?",
  "Mande um áudio de 5 segundos suspirando no ouvido de alguém no WhatsApp.",
  "Dê um beijo de 10 segundos na pessoa que você acha mais atraente da roda.",
  "Descreva o encontro perfeito que terminaria com os dois sem roupa.",
  "Você prefere dominar ou ser dominado(a)? Justifique com um exemplo real.",
  "Tire uma peça de roupa (exceto acessórios pequenos) ou beba dois shots.",
  "Qual é a sua opinião sobre fazer amor no primeiro encontro?",
  "Qual a parte do corpo das pessoas que mais te desperta desejos?",
  "Fale sobre a sua experiência sexual mais engraçada ou desastrosa.",
  "Deixe que alguém morda seus lábios suavemente por 5 segundos.",
  "Qual foi a maior loucura que você já fez por puro desejo físico?",
  "Beije a bochecha de três pessoas da roda, mas de forma extremamente lenta e provocativa.",
  "Você já mandou fotos íntimas (nudes)? Se sim, para quem foi o último?",
  "Fique sem camisa/blusa até o final da rodada ou beba 3 goles grandes.",
  "Qual perfume ou cheiro você acha irresistível em alguém?",
  "Diga algo que você gostaria de experimentar na cama, mas ainda não teve coragem.",
  "Dê um selinho triplo (três beijinhos rápidos) na pessoa à sua frente.",
  "Se você pudesse me fazer uma pergunta sem restrições e eu tivesse que responder a verdade, qual seria?",
  "Qual é o seu fetiche por roupas (lingeries, fantasias, ternos)?",
  "Deixe que a pessoa à sua esquerda faça cócegas em você por 15 segundos sem que você possa reclamar.",
  "Qual foi a última pessoa com quem você teve um sonho erótico?",
  "Se você pudesse tocar qualquer parte do corpo de alguém aqui sem julgamentos, onde tocaria?",
  "Você prefere luz acesa ou apagada na hora H? Explique o porquê.",
  "Coma um pedaço de fruta ou aperitivo diretamente da boca de alguém da sala.",
  "Qual o maior número de vezes que você já fez amor no mesmo dia?",
  "Tire uma foto sexy agora com alguém da roda e guarde na galeria.",
  "Qual é o seu limite quando se trata de jogos na cama?",
  "Passe a mão pelo cabelo de alguém aqui de forma super lenta enquanto olha nos olhos.",
  "Você já foi pego(a) no flagrante? Conte como foi.",
  "Qual o lugar público mais arriscado onde você já flertou ou beijou de verdade?",
  "Se você pudesse apagar um momento íntimo do seu passado por puro arrependimento, qual seria?",
  "Faça um elogio sussurrado e safado para a pessoa que está sentada ao seu lado.",
  "Quem da sala você acha que tem a voz mais sensual?",
  "Você seria capaz de fazer um strip-tease para alguém aqui? Se sim, mostre um movimento rápido.",
  "Diga qual o tipo de beijo que você mais gosta (lento, selvagem, com mordida).",
  "Mostre a sua marca de nascença ou cicatriz em um lugar mais escondido do seu corpo.",
  "Deixe que alguém passe um cubo de gelo no seu pescoço.",
  "Você já teve alguma fantasia com alguém que é comprometido?",
  "Qual a sua tática infalível para seduzir alguém em uma festa?",
  "Escreva 'Quero você' nas costas de alguém usando o dedo, e a pessoa tem que adivinhar quem escreveu.",
  "Você prefere manhã, tarde ou noite para momentos íntimos? E por quê?",
  "Sente no colo de alguém da roda por duas rodadas inteiras.",
  "Qual a maior diferença de idade que você já teve com um parceiro ou parceira?",
  "Se você tivesse que descrever o seu estilo na cama em três palavras, quais seriam?",
  "Dê um beijo de cinema na pessoa à sua escolha, ou beba a bebida de todos na mesa.",
  "Você já usou brinquedos íntimos com alguém? Fale sobre a experiência.",
  "Qual foi o elogio mais picante ou inesquecível que você já recebeu?",
  "Beije a nuca de alguém da roda por 5 segundos.",
  "Qual é a sua zona erógena mais sensível que pouca gente conhece?",
  "Se você ganhasse um vale-tudo de 24 horas para fazer o que quiser com alguém aqui, o que faria?",
  "Passe um batom e dê um beijo na bochecha ou pescoço de alguém para deixar a marca.",
  "Qual a primeira coisa que você repara fisicamente em alguém quando está interessado(a)?",
  "Você prefere beijo com muito ou pouco contato físico corporal?",
  "Fale sobre uma fantasia sua que envolva mais de duas pessoas.",
  "Deixe que a pessoa à sua direita tire uma peça de roupa sua.",
  "Você já teve atração por algum amigo ou amiga muito próximo(a) e nunca contou?",
  "Faça uma massagem nos pés ou nas mãos de alguém por 1 minuto de forma relaxante.",
  "Qual foi a situação mais constrangedora que você já passou por causa de um flerte?",
  "Diga qual a peça de roupa íntima que você está usando hoje (cor, estilo).",
  "Beije a testa, a bochecha e depois os lábios da pessoa à sua esquerda.",
  "Qual música você colocaria para tocar em um momento de pura sedução?",
  "Você já fez amor ao ar livre? Onde foi?",
  "Diga quem da sala você acha que é o/a mais selvagem na intimidade.",
  "Tire a meia de alguém usando apenas os dentes.",
  "Você tem alguma fantasia com fardas, uniformes ou roupas específicas?",
  "Deixe que alguém desenhe um coração na sua coxa usando uma caneta.",
  "Qual a sua maior mentira dita para conseguir levar alguém para a cama?",
  "Você prefere tapinhas, puxões de cabelo ou algo mais carinhoso?",
  "Fique de mãos dadas com a pessoa à sua direita de forma bem firme até a próxima rodada.",
  "Qual é a sua opinião sobre amor livre ou relacionamentos abertos?",
  "Diga o que você faria se pudesse passar uma noite em um motel de luxo com alguém daqui.",
  "Deixe que alguém lamba uma gota de bebida no seu pescoço.",
  "Você já fez ou gostaria de fazer um ensaio fotográfico sensual?",
  "Quem aqui na roda você acha que tem a mente mais poluída?",
  "Sussurre para a pessoa ao seu lado o que você achou mais sexy nela hoje.",
  "Qual o lugar mais estranho onde você já sentiu tesão do nada?",
  "Você já beijou mais de uma pessoa na mesma noite? Quantas?",
  "Faça contato visual com a pessoa à sua frente por 30 segundos sem desviar e sem rir.",
  "Qual parte do seu próprio corpo você acha mais atraente e sexy?",
  "Você prefere romance meloso ou pura paixão carnal no dia a dia?",
  "Dê um abraço apertado e demorado (pelo menos 15 segundos) na pessoa da sua escolha.",
  "Qual é a sua fantasia número um envolvendo água (chuveiro, piscina, mar)?",
  "Você já flertou com alguém só para conseguir alguma vantagem ou favor?",
  "Mostre sua habilidade de beijo técnico fazendo movimentos com a língua no ar ou beijando um copo.",
  "Você prefere beijar alguém mais alto ou mais baixo que você?",
  "Diga uma frase safada que você gostaria de ouvir na hora H.",
  "Dê um beijo na mão de todos os participantes, mas de um jeito bem provocante.",
  "Você já mandou mensagem por engano para um ex enquanto estava com outra pessoa?",
  "Qual foi o máximo de tempo que você já ficou sem relações íntimas por opção própria?",
  "Faça uma dança rápida e descontraída (tipo dança do ventre ou funk) por 10 segundos.",
  "Quem na roda você acha que se veste de forma mais provocante ou estilosa?",
  "Você já se apaixonou à primeira vista por puro desejo físico?",
  "Fale uma palavra no ouvido de alguém com a voz mais rouca e sensual que conseguir.",
  "Você prefere encontros clássicos (jantar, cinema) ou algo mais direto e íntimo?",
  "Deixe que alguém morda levemente o seu dedo indicador.",
  "Qual a maior loucura que você aceitaria fazer na cama por amor ou desejo?",
  "Você já usou aplicativos de relacionamento? Qual foi a sua melhor ou pior experiência?",
  "Faça carinho na nuca de alguém da roda até a sua próxima vez de jogar.",
  "Qual é a primeira palavra que vem à sua mente quando pensa em sedução?",
  "Diga qual o maior clichê erótico que você adoraria realizar.",
  "Coma um chocolate ou doce de um jeito bem provocativo olhando para alguém.",
  "Você já fingiu satisfação na cama? Se sim, por que fez isso?",
  "Quem aqui na sala tem o sorriso mais malicioso?",
  "Dê três beijos estalados no pescoço da pessoa à sua direita.",
  "Qual o seu maior arrependimento amoroso ou sexual?",
  "Se você pudesse trocar de corpo com qualquer pessoa aqui por uma noite, quem seria?",
  "Fique bem pertinho do rosto de alguém, quase encostando os lábios, por 10 segundos.",
  "Você prefere perfumes doces, amadeirados ou cítricos em um parceiro?",
  "Conte um detalhe sobre a última vez que você teve um momento íntimo.",
  "Deixe que a pessoa à sua frente faça um elogio sincero sobre a sua boca.",
  "Você prefere beijar de olhos abertos ou fechados? Por quê?",
  "Mostre a sua tela de bloqueio e explique por que escolheu essa imagem.",
  "Diga qual é a maior qualidade que um bom parceiro íntimo precisa ter.",
  "Fique de costas para a pessoa à sua esquerda e deixe que ela abrace você por trás.",
  "Você já teve atração por alguém muito mais velho ou muito mais novo?",
  "Qual a sua maior fantasia envolvendo viagens ou locais exóticos?",
  "Deixe que alguém dê um tapinha leve na sua bunda (se todos estiverem confortáveis).",
  "Você prefere massagem relaxante ou massagem sensual com óleos?",
  "Qual é o seu maior ponto fraco físico (onde você não resiste ao toque)?",
  "Fale sobre o sonho mais picante que você se lembra de ter tido.",
  "Faça carinho no braço de alguém usando a ponta dos dedos de forma bem suave.",
  "Você já mandou uma foto ousada por engano no grupo da família ou trabalho?",
  "Diga qual a roupa que você acha mais sexy em outra pessoa.",
  "Beije o canto da boca da pessoa que você achar mais atraente.",
  "Você já tomou banho acompanhado(a) recentemente? Conte como foi.",
  "Quem na roda você acha que tem o olhar mais penetrante?",
  "Fique cara a cara com alguém e imite uma cena clássica de romance por 10 segundos.",
  "Você já se sentiu atraído(a) por alguém apenas ouvindo a voz dessa pessoa?",
  "Deixe que alguém cheire o seu pescoço bem de perto por 5 segundos.",
  "Qual a sua posição favorita para dormir com alguém após uma noite intensa?",
  "Você prefere mensagens picantes durante o dia ou conversas sussurradas à noite?",
  "Diga quem da roda você levaria para uma ilha deserta por uma semana.",
  "Dê um beijo na bochecha de cada pessoa da roda.",
  "Você já teve um amor proibido? Como foi lidar com isso?",
  "Faça uma cara de sedução para a câmera do seu celular e mostre para a roda.",
  "Quem aqui você acha que seria o melhor parceiro de crime em uma aventura?",
  "Você já beijou alguém do mesmo gênero? Como foi?",
  "Deixe que a pessoa à sua esquerda escreva uma palavra sexy no seu braço com batom.",
  "Qual o seu maior segredo para manter o fogo aceso em uma relação?",
  "Você prefere mordidas nos lábios, no pescoço ou na orelha?",
  "Diga um elogio ousado para a pessoa que está sentada diretamente na sua frente.",
  "Você já fez amor em um carro? Qual o nível de adrenalina?",
  "Deixe que alguém escolha uma música sexy e faça você dublar a letra olhando para alguém.",
  "Qual o maior tabu que você quebrou na sua vida íntima?",
  "Você prefere carinho antes, durante ou depois da ação principal?",
  "Mostre para alguém da roda o último print que você tirou no celular.",
  "Você já teve alguma experiência marcante em uma festa de formatura ou casamento?",
  "Dê um beijo longo na palma da mão da pessoa à sua direita.",
  "Quem aqui você acha que tem a risada mais contagiante e atraente?",
  "Você já fez alguma promessa ousada que teve que cumprir depois?",
  "Deixe que a pessoa à sua frente escolha um apelido carinhoso ou safado para você até o fim do jogo.",
  "Qual o seu maior fetiche visual (por exemplo, olhar no espelho)?",
  "Você já flertou com alguém apenas usando troca de olhares de longe?",
  "Passe a língua nos lábios lentamente enquanto olha para alguém da roda.",
  "Qual a sua opinião sobre o uso de vendas ou algemas leves na intimidade?",
  "Diga o nome da pessoa da sala que tem os lábios mais bonitos.",
  "Você já participou de alguma brincadeira de beijo na infância ou adolescência?",
  "Deixe que alguém massageie suas têmporas ou couro cabeludo por 1 minuto.",
  "Qual é a sua fantasia mais secreta que envolve fantasias ou jogos de RPG?",
  "Você prefere um parceiro calmo e carinhoso ou intenso e ousado?",
  "Dê um suspiro no pescoço da pessoa à sua esquerda.",
  "Você já teve um encontro duplo que terminou de forma inesperada?",
  "Diga o que você faria se encontrasse a pessoa à sua frente em uma praia de nudismo.",
  "Deixe que alguém morda levemente o seu ombro por cima da roupa.",
  "Qual o maior elogio que você pode fazer sobre o desempenho de alguém na cama?",
  "Você já teve uma noite inesquecível com alguém cujo nome você nem lembrava direito?",
  "Sussurre a palavra 'Quero' no ouvido da pessoa à sua direita.",
  "Quem aqui na roda você acha que seria a melhor companhia para uma noite de balada insana?",
  "Você prefere flertar online (mensagens) ou pessoalmente (cara a cara)?",
  "Dê um beijo estalado na bochecha da pessoa à sua esquerda e depois na da direita.",
  "Qual a sua maior fantasia que envolve posições arriscadas ou acrobáticas?",
  "Você já fez uma massagem com chocolate, mel ou chantilly?",
  "Diga qual a maior loucura que você faria agora por um beijo da pessoa que você quer.",
  "Fique abraçado(a) com a pessoa à sua frente por 30 segundos em silêncio.",
  "Você prefere um flerte misterioso ou alguém que vai direto ao ponto?",
  "Deixe que a pessoa à sua direita mexa no seu cabelo por 1 rodada.",
  "Qual a parte do corpo de um parceiro que você considera mais subestimada eroticamente?",
  "Você já beijou alguém na chuva de forma cinematográfica?",
  "Diga uma fantasia que você tem e que gostaria de realizar ainda este ano.",
  "Diga qual a maior loucura que você aceitaria fazer em um local público.",
  "Mande um emoji de coração de olhos fechados para a primeira pessoa sugerida no seu compartilhamento.",
  "Se você pudesse sussurrar algo no ouvido da pessoa à sua escolha agora, o que diria?"
];

async function main() {
  console.log("Seeding cards...");
  
  // Clear existing cards
  await prisma.card.deleteMany();
  
  // Seed cards
  for (const content of cards) {
    await prisma.card.create({
      data: { content },
    });
  }
  
  const count = await prisma.card.count();
  console.log(`Seeding complete. Seeded ${count} cards.`);
}

main()
  .catch((e) => {
    console.error("Error seeding cards:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
